-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS BOARD
LEFT JOIN USED_GOODS_USER AS USERS
ON WRITER_ID = USER_ID
WHERE BOARD.STATUS ="DONE"
GROUP BY USERS.USER_ID
HAVING TOTAL_SALES>=700000
ORDER BY TOTAL_SALES